---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
helmGlobals:
  chartHome: ../../../vendor
helmCharts:
  - name: openshift-external-secrets
    includeCRDs: true
    releaseName: openshift-external-secrets
    valuesFile: values.yaml
resources:
  - service-ca-cm.yaml
