---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - rbac.yaml
  - job.yaml
  - service-ca-cm.yaml
configMapGenerator:
  - name: vault-config-scripts
    files:
      - configure.sh
      - hub.hcl
