---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
helmGlobals:
  chartHome: ../../../vendor
helmCharts:
  - name: hashicorp-vault
    includeCRDs: true
    releaseName: vault
